version: "3.4"

services:
  pgAdmin:
    restart: always
    image: dpage/pgadmin4
    ports:
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 1234@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
      - pgadmin:/var/lib/pgadmin
  postgres:
    restart: always
    image: postgres
    container_name: "postgres_container"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: me
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: testDb
    volumes:
      - pgvol:/var/lib/postgresql/data
  app:
    depends_on:
      - postgres
    build:
      context: ../
      dockerfile: ./docker/server.Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ../app/src:/app/src

volumes:
  pgvol:
  pgadmin:
