FROM node:12.13-alpine

WORKDIR /app

COPY ./package*.json ./

RUN npm install

# install nest-cli
RUN npm i -g @nestjs/cli
RUN npm cache clean --force

COPY . .

ENTRYPOINT [ "npm","run", "start:debug" ]